format_version: v1.0
type: UniqueComponent
attributes: {id: dac}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DAC_CHANNEL_0_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: DAC_CHANNEL_0_REFRESH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: DAC_CHANNEL_EVENT_STARTEI0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: DAC_REFSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '30', y: '100', id: dac}
