format_version: v1.0
type: UniqueComponent
attributes: {id: tram}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TRAM_DRP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: File
    attributes: {id: TRAM_FILE_0}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: SECURE}
  - type: File
    attributes: {id: TRAM_FILE_1}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: SECURE}
  - type: File
    attributes: {id: TRAM_FILE_2}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_DEFINITIONS_SECURE_H_INCLUDES}
  - type: Boolean
    attributes: {id: TRAM_SILENT_ACCESS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: File
    attributes: {id: TRAM_SYS_INIT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_SECURE_INIT_C_SYS_INITIALIZE_PERIPHERALS}
  - type: Boolean
    attributes: {id: TRAM_TAMPER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '170', y: '80', id: tram}
