configName: pic32cm_cpro_ls60
folderName: pic32cm_cpro_ls60_NonSecure
format_version: v1.0
frameworkPath: ..\..\..\..\..\..
processor: PIC32CM5164LS60100
projectName: usart_sof_interrupt_pic32cm_cpro_ls60_NonSecure
settings:
  PackageFilter: csp;csp_apps_pic32cm_le_ls;csp_apps_sam_c20_c21;csp_apps_sam_d5x_e5x;csp_apps_sam_g55;csp_apps_sam_l10_l11;csp_apps_sam_l21;dev_packs;harmony-services;quick_docs
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-LS_DFP\1.0.135\PIC32CM-LS60\atdf\PIC32CM5164LS60100.atdf
