format_version: v1.0
type: UniqueComponent
attributes: {id: rtc}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: RTC_MODE0_EVCTRL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '32'}
  - type: Boolean
    attributes: {id: RTC_MODE0_EVCTRL_PEREO5_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '192', y: '133', id: rtc}
