format_version: v1.0
type: UniqueComponent
attributes: {id: pm}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: PLCFG_PLDIS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: File
    attributes: {id: PM_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: SECURE}
  - type: KeyValueSet
    attributes: {id: PM_PLCFG_PLSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pm, value: '1'}
      - type: User
        attributes: {value: '1'}
  - type: File
    attributes: {id: PM_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: SECURE}
  - type: Boolean
    attributes: {id: PM_STDBYCFG_BBIASHS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: PM_STDBYCFG_BBIASTR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: PM_STDBYCFG_PDCFG}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: File
    attributes: {id: PM_SYS_DEF}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_DEFINITIONS_SECURE_H_INCLUDES}
- type: ElementPosition
  attributes: {x: '310', y: '60', id: pm}
