format_version: v1.0
type: UniqueComponent
attributes: {id: supc}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: SUPC_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: SECURE}
  - type: File
    attributes: {id: SUPC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: SECURE}
  - type: File
    attributes: {id: SUPC_SYS_DEF}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_DEFINITIONS_SECURE_H_INCLUDES}
  - type: File
    attributes: {id: SUPC_SYS_INT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_SECURE_INIT_C_SYS_INITIALIZE_PERIPHERALS}
  - type: Boolean
    attributes: {id: SUPC_VREG_LPEFF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SUPC_VREG_SEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SUPC_VREG_STDBYPL0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '150', y: '120', id: supc}
