format_version: v1.0
type: UniqueComponent
attributes: {id: core}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: COMPILER_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Boolean
    attributes: {id: CONFIG_CLOCK_DFLL48M_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Integer
    attributes: {id: CPU_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '48000000'}
  - type: Menu
    attributes: {id: CoreIARMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Menu
    attributes: {id: CoreKEILMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: DEVICE_SECURITY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Integer
    attributes: {id: DFLL48M_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '48000000'}
  - type: Hex
    attributes: {id: FUSE_SYMBOL_VALUE15}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '682'}
  - type: Hex
    attributes: {id: FUSE_SYMBOL_VALUE16}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64'}
  - type: Hex
    attributes: {id: FUSE_SYMBOL_VALUE18}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '256'}
  - type: KeyValueSet
    attributes: {id: FUSE_SYMBOL_VALUE35}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '1'}
  - type: Hex
    attributes: {id: FUSE_SYMBOL_VALUE62}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3900076982'}
  - type: Hex
    attributes: {id: FUSE_SYMBOL_VALUE63}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64'}
  - type: Hex
    attributes: {id: FUSE_SYMBOL_VALUE64}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: Hex
    attributes: {id: FUSE_SYMBOL_VALUE65}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '682'}
  - type: Integer
    attributes: {id: GCLK_0_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '48000000'}
  - type: KeyValueSet
    attributes: {id: GCLK_0_SRC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '3'}
  - type: Integer
    attributes: {id: GCLK_1_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Integer
    attributes: {id: GCLK_2_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Integer
    attributes: {id: GCLK_3_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Integer
    attributes: {id: GCLK_4_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Integer
    attributes: {id: GCLK_5_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Integer
    attributes: {id: GCLK_6_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Integer
    attributes: {id: GCLK_7_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: ListEntry
    attributes: {id: GCLK_CODE}
    children:
    - type: Attributes
      children:
      - type: StringArray
        attributes: {id: values}
        children:
        - type: Values
          children:
          - {type: Value, value: '    DFLL48M_Initialize();'}
          - {type: Value, value: '    GCLK0_Initialize();'}
  - type: Boolean
    attributes: {id: GCLK_CYCLE_FORMED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: GENERATE_SECURE_BOOT_MAIN_FILE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: IDAU_ANSC_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '16'}
      - type: User
        attributes: {value: '64'}
  - type: KeyValueSet
    attributes: {id: IDAU_AS_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '1024'}
      - type: User
        attributes: {value: '682'}
  - type: KeyValueSet
    attributes: {id: IDAU_BNSC_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '64'}
  - type: KeyValueSet
    attributes: {id: IDAU_BOOTPROT_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '682'}
  - type: KeyValueSet
    attributes: {id: IDAU_RS_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '256'}
  - type: String
    attributes: {id: KEIL_STACK_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x1200'}
  - type: File
    attributes: {id: NONSECURE_ENTRY_C}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: nonsecure_entry_boot.c}
  - type: File
    attributes: {id: NONSECURE_ENTRY_H}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: nonsecure_entry_boot.h}
  - type: Hex
    attributes: {id: NON_SEC_START_ADDRESS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '349184'}
  - type: KeyValueSet
    attributes: {id: NVIC_1_0_SECURITY_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: String
    attributes: {id: PIN_59_DIR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Out}
  - type: String
    attributes: {id: PIN_59_FUNCTION_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: LED0}
  - type: String
    attributes: {id: PIN_59_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: GPIO}
  - type: String
    attributes: {id: PIN_59_INEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ''}
  - type: String
    attributes: {id: PIN_59_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ''}
  - type: String
    attributes: {id: PIN_59_PERIPHERAL_FUNCTION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: GPIO}
  - type: Boolean
    attributes: {id: PORT_GROUP_0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: PORT_GROUP_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: PORT_GROUP_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: PORT_GROUP_2_DIR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x80000'}
  - type: String
    attributes: {id: PORT_GROUP_2_PAD_19}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: PC19}
  - type: String
    attributes: {id: PORT_GROUP_2_PINCFG19}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x0'}
  - type: Boolean
    attributes: {id: PORT_GROUP_2_PIN_19_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: PORT_GROUP_2_PMUX9}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x0'}
  - type: String
    attributes: {id: PORT_REG_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: PORT_SEC}
  - type: Hex
    attributes: {id: SEC_START_ADDRESS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '174592'}
  - type: Setting
    attributes: {id: SEC_XC32_LINKER_CMSE_FLAG}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: value}
        children:
        - {type: Value, value: '--out-implib=../../../NonSecure/firmware/pic32cm_ls00_cpro_NonSecure.X/pic32cm_ls00_cpro_Secure_boot_sg_veneer.lib
            ,--cmse-implib'}
  - type: String
    attributes: {id: SYSTICK_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0xBB80'}
  - type: Integer
    attributes: {id: SYSTICK_PERIOD_US}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '1000'}
  - type: String
    attributes: {id: SYSTICK_SECURE_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0xbb80'}
  - type: Integer
    attributes: {id: SYSTICK_SECURE_PERIOD_US}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '1000'}
  - type: Boolean
    attributes: {id: WDT_SET_NON_SECURE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Setting
    attributes: {id: XC32_LINKER_LIBRARY_}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: value}
        children:
        - {type: Value, value: '-l:pic32cm_ls00_cpro_Secure_boot_sg_veneer.lib'}
  - type: Setting
    attributes: {id: XC32_LINKER_MACRO}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Setting
    attributes: {id: XC32_LINKER_MACRO_ANSC_SIZE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: value}
        children:
        - {type: Value, value: ANSC_SIZE=0x800}
  - type: Setting
    attributes: {id: XC32_LINKER_MACRO_AS_SIZE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: value}
        children:
        - {type: Value, value: AS_SIZE=0x2aa00}
  - type: Setting
    attributes: {id: XC32_LINKER_MACRO_AS_SIZE_NON_SECURE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: value}
        children:
        - {type: Value, value: AS_SIZE=0x2aa00}
  - type: Setting
    attributes: {id: XC32_LINKER_MACRO_BNSC_SIZE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: value}
        children:
        - {type: Value, value: BNSC_SIZE=0x800}
  - type: Setting
    attributes: {id: XC32_LINKER_MACRO_BOOTPROT_SIZE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: value}
        children:
        - {type: Value, value: BOOTPROT_SIZE=0x2aa00}
  - type: Setting
    attributes: {id: XC32_LINKER_MACRO_BOOTPROT_SIZE_NON_SECURE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: value}
        children:
        - {type: Value, value: BOOTPROT_SIZE=0x2aa00}
  - type: Setting
    attributes: {id: XC32_LINKER_MACRO_SECURE_BOOTLOADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '300', y: '20', id: core}
