configName: pic32cm_ls60_cpro
folderName: pic32cm_ls60_cpro_NonSecure
format_version: v1.0
frameworkPath: ..\..\..\..\..\..
processor: PIC32CM5164LS60100
projectName: secure_tc_pic32cm_ls60_cpro_NonSecure
settings:
  PackageFilter: csp;csp_apps_pic32cm_le_ls
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-LS_DFP\1.0.110\PIC32CM-LS60\atdf\PIC32CM5164LS60100.atdf
