configName: pic32cm_le00_curiosity_pro
folderName: pic32cm_le00_curiosity_pro
format_version: v1.0
frameworkPath: ..\..\..\..\..
processor: PIC32CM5164LE00100
projectName: sercom_usart_start_of_frame_interrupt_pic32cm_le00_curiosity_pro
settings:
  PackageFilter: csp;csp_apps_pic32cm_le_ls;csp_apps_sam_c20_c21;csp_apps_sam_d5x_e5x;csp_apps_sam_g55;csp_apps_sam_l10_l11;csp_apps_sam_l21;dev_packs;harmony-services;quick_docs
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-LE_DFP\1.0.134\atdf\PIC32CM5164LE00100.atdf
