format_version: v1.0
type: UniqueComponent
attributes: {id: tram}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TRAM_DRP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TRAM_SILENT_ACCESS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TRAM_TAMPER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '137', y: '135', id: tram}
