configName: pic32cm_le00_curiosity_pro
folderName: pic32cm_le00_curiosity_pro
format_version: v1.0
frameworkPath: ..\..\..\..
processor: PIC32CM5164LE00100
projectName: low_power_pic32cm_le00_curiosity_pro
settings:
  PackageFilter: csp;csp_apps_pic32cm_le_ls
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-LE_DFP\1.0.129\atdf\PIC32CM5164LE00100.atdf
