format_version: v1.0
type: UniqueComponent
attributes: {id: nvmctrl}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: FAST_WAKEUP_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: NVMCTRL_CACHE_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Combo
    attributes: {id: NVMCTRL_WRITE_POLICY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: AUTOMATIC}
  - type: Integer
    attributes: {id: NVM_RWS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: nvmctrl, value: '2'}
  - type: Boolean
    attributes: {id: SILENT_ACCESS_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TAMPER_DETECTION_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '20', y: '20', id: nvmctrl}
