format_version: v1.0
type: UniqueComponent
attributes: {id: rtc}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: RTC_MODE0_EVCTRL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '49152'}
  - type: Boolean
    attributes: {id: RTC_MODE0_EVCTRL_OVFEO_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: RTC_MODE0_INTERRUPT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Hex
    attributes: {id: RTC_MODE1_EVCTRL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '16384'}
  - type: Hex
    attributes: {id: RTC_MODE2_EVCTRL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '16384'}
  - type: Hex
    attributes: {id: RTC_TAMPCTRL_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '16842753'}
  - type: KeyValueSet
    attributes: {id: TAMP_CHANNEL0_ACTION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: TAMP_CHANNEL0_DEBNC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: TAMP_CHANNEL0_LEVEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: TAMP_EVENTOUT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '310', y: '60', id: rtc}
