configName: pic32cm_ls00_cpro
folderName: trustZone_with_SBoot_BS_pic32cm_ls00_cpro_NonSecure
format_version: v1.0
frameworkPath: C:\HF
processor: PIC32CM5164LS00100
projectName: trustZone_with_SBoot_BS_pic32cm_ls00_cpro_NonSecure
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'true'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CM-LS_DFP\1.0.141\PIC32CM-LS00\atdf\PIC32CM5164LS00100.atdf
