configName: pic32cm_le00_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32CM5164LE00100
projectName: ''
settings:
  PackageFilter: bsp;core;csp;csp_apps_pic32cm_jh00_jh01;csp_apps_pic32cm_le00_ls00;csp_apps_pic32cm_mc00;csp_apps_pic32cx_bz24_bz25;gfx;motor_control;touch;validation;x2c;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-LE_DFP\1.0.74\atdf\PIC32CM5164LE00100.atdf
